platform:ios,'8.0'
pod 'AFNetworking', '2.5.4'
pod 'IQKeyboardManager'
pod 'JSONModel'
pod 'KVOController'
pod 'MagicalRecord'
pod 'RESideMenu'
pod 'SDWebImage'
pod 'SVProgressHUD'
pod 'HexColors'
pod 'pop'
#pod 'EaseMobSDK'
#pod 'TextFieldEffects', '0.4.2'
