xcodeproj 'org.mobiletrain.open-remote.xcodeproj'

platform:ios,'8.0'
pod 'AFNetworking'
pod 'HexColors'
pod 'IQKeyboardManager'
pod 'JSONModel'
pod 'KVOController'
pod 'MagicalRecord'
pod 'Mantle'
pod 'RESideMenu'
pod 'SDWebImage'
pod 'SVProgressHUD'
pod 'pop'
#pod 'EaseMobSDK'
#pod 'TextFieldEffects', '0.4.2'
