xcodeproj 'org.mobiletrain.open-remote.xcodeproj'

platform:ios,'8.0'
pod 'AFNetworking'
pod 'HexColors'
pod 'IQKeyboardManager'
pod 'JSONModel'
pod 'KVOController'
pod 'MagicalRecord'
pod 'Mantle'
pod 'RESideMenu'
pod 'SDWebImage'
pod 'SVProgressHUD'
pod 'pop'
pod 'ShareSDK2'
pod 'ShareSDK2/UI'
pod 'ShareSDK2/Connection/SinaWeibo'
pod 'ShareSDK2/Connection/WeChat'
pod 'EaseMobSDK'
pod 'MOBFoundation'
pod 'EaseUI', :git => 'https://github.com/easemob/easeui-ios-cocoapods.git'
#pod 'TextFieldEffects', '0.4.2'
